### ISSUE TITLE
Invalid paramerter name: ATMAcore

### ISSUE THREAD

**Issue by sobertie** [Gallicchio-Lab/AToM-OpenMM#45]
i am using AToM-OpenMM with HDAC11 protein with its known inhibitor. During replica exchange given the command for i in hdac11-* ; do ( cd $i ; bash ./run.sh ) ; done: the following errors occurs -

Traceback (most recent call last):
  File "/home/mohon/AToM-OpenMM/rbfe_explicit.py", line 43, in <module>
    rx = openmm_job_RBFE(commandFile, options=None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/AToM-OpenMM/openmm_async_re.py", line 420, in __init__
    self.service_worker = OMMWorkerATM(self.basename, service_ommsys, self.keywords, compute = False, logger = self.logger)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mohon/AToM-OpenMM/ommworker.py", line 53, in __init__
    self.start_worker()
  File "/home/mohon/AToM-OpenMM/ommworker.py", line 94, in start_worker
    self._openmm_worker_makecontext()
  File "/home/mohon/AToM-OpenMM/ommworker.py", line 249, in _openmm_worker_makecontext
    self.simulation.loadState(self.basename + "_0.xml")
  File "/home/mohon/anaconda3/envs/atm/lib/python3.11/site-packages/openmm/app/simulation.py", line 350, in loadState
    self.context.setState(mm.XmlSerializer.deserialize(xml))
  File "/home/mohon/anaconda3/envs/atm/lib/python3.11/site-packages/openmm/openmm.py", line 16652, in setState
    return _openmm.Context_setState(self, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Called setParameter() with invalid parameter name: ATMAcore

What is the error here ?

**Comment by egallicc** [comment]
I am unable to reproduce this problem. The CDK2 example runs fine.

Did you install OpenMM 8.1beta according to the [instructions](https://github.com/Gallicchio-Lab/AToM-OpenMM#readme)? Did you install the [AToM-OpenMM 8.1beta release](https://github.com/Gallicchio-Lab/AToM-OpenMM/releases/tag/v8.1.0beta) or the [master branch](https://github.com/Gallicchio-Lab/AToM-OpenMM)?

**Comment by sobertie** [comment]
I am using my own protein, HDAC11. If I give you protein ligand complexes,
can you please generate input files for that ? And reproduce the protocol
for my HDAC11 protein ? I will also try it in my system. I already have
input files though. But it requires ATM force plug in ./prep.sh execution.
Which is deprecated in newer version. So I am going through incompatibility
issues.

**Comment by sobertie** [comment]
And yes I am using 8.1 version.

**Comment by sobertie** [comment]
Here is my generated input files for HDAC11.

**Comment by egallicc** [comment]
The chemical system is probably irrelevant. The error you are encountering could be caused by running the `structprep` step with one version of OpenMM and the production with another version, somehow.

AToM-OpenMM with OpenMM 8.1beta does not need the `openmm-atmmetaforce` plugin. The ATM potential is implemented directly in ATMForce().

**Comment by sobertie** [comment]
Ok, thanks for the clarification.
