### ISSUE TITLE
AToM fails to detect cuda device temoa1 ABFE example

### ISSUE THREAD

**Issue by blakemertz** [Gallicchio-Lab/AToM-OpenMM#67]
I have installed and set up my ATM environment as per the installation instructions on github. However, when I went to do the structure prep step in the temoa ABFE example, I got the following error:

```
(atm8.1) blakem@bm-mod-laptop:/media/Data/binaries/github/AToM-OpenMM-8.1.0/examples/ABFE/temoa-g1$ python ../../../abfe_structprep.py temoa-g1_asyncre.cntl 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.

========================================
AToM ABFE Structure Preparation         
========================================

Started at: Mon Jan  8 13:38:16 2024
Input file: temoa-g1_asyncre.cntl

Traceback (most recent call last):
  File "/media/Data/binaries/github/AToM-OpenMM-8.1.0/examples/ABFE/temoa-g1/../../../abfe_structprep.py", line 434, in <module>
    do_mintherm(keywords, restrain_solutes, logger)
  File "/media/Data/binaries/github/AToM-OpenMM-8.1.0/examples/ABFE/temoa-g1/../../../abfe_structprep.py", line 93, in do_mintherm
    simulation = Simulation(syst.topology, syst.system, syst.integrator, platform, platform_properties)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Data/binaries/miniconda3/envs/atm8.1/lib/python3.12/site-packages/openmm/app/simulation.py", line 106, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/Data/binaries/miniconda3/envs/atm8.1/lib/python3.12/site-packages/openmm/openmm.py", line 8644, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: No compatible CUDA device is available
```
I have a cuda compatible device on my laptop:

```
(atm8.1) blakem@bm-mod-laptop:/media/Data/binaries/github/AToM-OpenMM-8.1.0/examples/ABFE/temoa-g1$ nvidia-smi 
Mon Jan  8 13:57:45 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   41C    P8    11W /  54W |    122MiB /  6144MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1188      G   /usr/lib/xorg/Xorg                 22MiB |
|    0   N/A  N/A    454086      G   .../bin/Linux-x86_64/maestro       95MiB |
+-----------------------------------------------------------------------------+
```
so it's not clear to me why I am generating this error message. Do I need to set the LOCAL_OPENMM environment variable before running this step?

**Comment by egallicc** [comment]
Test the OpenMM installation http://docs.openmm.org/latest/userguide/application/01_getting_started.html#installing-openmm

**Comment by blakemertz** [comment]
Forgot that I had just upgraded my nvidia drivers and didn't reboot my laptop. openMM working in the atm8.1 environment as it should now. Thanks for the sanity check!
