### ISSUE TITLE
Error when Running Tutorial

### ISSUE THREAD

**Issue by jianmingm** [Gallicchio-Lab/AToM-OpenMM#74]
When i was running fkbp-thi example, i got the following error and do not have a good idea on how to solve this. The node file i used is the following. 
localhost,0:0,1,GPU,,/tmp
localhost-cpu,0:0,8,CPU,,/tmp

Traceback (most recent call last):
  File "/home/mjianming/Softwares/AToM-OpenMM-8.1.1/abfe_explicit.py", line 43, in <module>
    rx = openmm_job_ABFE(commandFile, options=None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mjianming/Softwares/AToM-OpenMM-8.1.1/openmm_async_re.py", line 390, in __init__
    self.service_worker = OMMWorkerATM(self.basename, service_ommsys, self.keywords, compute = False, logger = self.logger)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mjianming/Softwares/AToM-OpenMM-8.1.1/ommworker.py", line 53, in __init__
    self.start_worker()
  File "/home/mjianming/Softwares/AToM-OpenMM-8.1.1/ommworker.py", line 94, in start_worker
    self._openmm_worker_makecontext()
  File "/home/mjianming/Softwares/AToM-OpenMM-8.1.1/ommworker.py", line 264, in _openmm_worker_makecontext
    self.simulation.loadState(self.basename + "_0.xml")
  File "/home/mjianming/Softwares/anaconda3/envs/atm8.1.1/lib/python3.12/site-packages/openmm/app/simulation.py", line 350, in loadState
    self.context.setState(mm.XmlSerializer.deserialize(xml))
  File "/home/mjianming/Softwares/anaconda3/envs/atm8.1.1/lib/python3.12/site-packages/openmm/openmm.py", line 11844, in setState
    return _openmm.Context_setState(self, state)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: in method 'Context_setState', argument 2 of type 'OpenMM::State const &'

**Comment by egallicc** [comment]
I am guessing that the ` self.basename + "_0.xml"` file is missing. Did you run `abfe_structprep.py` to generate the `*_0.xml` initial configuration?

Also, `GPU` is not a valid OpenMM platform. Try:
```
localhost,0:0,1,CUDA,,/tmp
localhost-cpu,0:0,8,CPU,,/tmp
```

**Comment by jianmingm** [comment]
Ah that's why. I wasn't very careful with the tutorial. Sorry for the confusion and Thanks so much!
