### ISSUE TITLE
CUDA error: unsupported PTX version

### ISSUE THREAD

**Issue by blakemertz** [Gallicchio-Lab/AToM-OpenMM#84]
The prior issues and documentation make it clear that AToM-openMM cannot be deployed on different GPU architectures. I have two different types of T4 GPU nodes on AWS (single GPU and 8x GPU), but they have a different CPU. Would this impact the ability for ATM to run between the two types of nodes?

I am currently extending the eralpha RBFE example calculation for a single complex (eralpha-2e-3a) for a total of 250 cycles. I completed 128 cycles on a single-GPU instance without any problems. However, I wanted to get more throughput, so I modified the run.sh SLURM script for that particular complex in order to run on an 8-GPU T4 node. The ATM installation in miniconda is the same for both the 1x and 8x GPU nodes since it is installed on a shared directory between the two types of AWS instances. My log file appears that the checkpoint files were read in correctly:
```
========================================
AToM RBFE Asynchronous Replica Exchange 
========================================

Started at: Tue May 14 16:02:57 2024
Input file: eralpha-2e-3a_asyncre.cntl

2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - compute nodes: localhost, localhost, localhost, localhost, localhost, localhost, localhost, localhost
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ASyncRE-OpenMM, Version 8.1.1
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - command_file = eralpha-2e-3a_asyncre.cntl
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - jobname = eralpha-2e-3a
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - Keywords:
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - JOB_TRANSPORT: LOCAL_OPENMM
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - BASENAME: eralpha-2e-3a
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - RE_SETUP: YES
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - TEMPERATURES: 300
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - LAMBDAS: 0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.50, 0.55, 0.60, 0.65, 0.70, 0.75, 0.80, 0.85, 0.90, 0.95, 1.00
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - DIRECTION:    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,    1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1,   -1
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - INTERMEDIATE:    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,    1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - LAMBDA1: 0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - LAMBDA2: 0.00, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40, 0.45, 0.50, 0.50, 0.45, 0.40, 0.35, 0.30, 0.25, 0.20, 0.15, 0.10, 0.05, 0.00
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ALPHA: 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - U0: 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - W0COEFF: 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00, 0.00
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - DISPLACEMENT:  22.0, 22.0, 22.0 
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - WALL_TIME: 1440
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - CYCLE_TIME: 10
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - CHECKPOINT_TIME: 1200
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - NODEFILE: nodefile
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - SUBJOBS_BUFFER_SIZE: 1.000000
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - PRODUCTION_STEPS: 20000
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - MAX_SAMPLES: 250
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - PRNT_FREQUENCY: 20000
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - TRJ_FREQUENCY: 20000
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - LIGAND1_ATOMS: ['3811', '3812', '3813', '3814', '3815', '3816', '3817', '3818', '3819', '3820', '3821', '3822', '3823', '3824', '3825', '3826', '3827', '3828', '3829', '3830', '3831', '3832', '3833', '3834', '3835', '3836', '3837', '3838', '3839', '3840', '3841', '3842', '3843', '3844', '3845', '3846', '3847', '3848', '3849', '3850', '3851', '3852']
.
.
.
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - POSRE_FORCE_CONSTANT: 25.0
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - POSRE_TOLERANCE: 1.5
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ALIGN_LIGAND1_REF_ATOMS: ['11', '6', '20']
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ALIGN_LIGAND2_REF_ATOMS: ['14', '9', '4']
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ALIGN_KF_SEP: 2.5
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ALIGN_K_THETA: 10.0
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ALIGN_K_PSI: 10.0
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - UMAX: 100.00
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - ACORE: 0.062500
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - UBCORE: 50.0
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - FRICTION_COEFF: 0.500000
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - TIME_STEP: 0.002
2024-05-14 16:02:57 - INFO     - async_re.openmm_async_re       - VERBOSE: no
2024-05-14 16:03:00 - INFO     - async_re.openmm_async_re       - Running with a 2.000000 fs time-step with bonded forces integrated 2 times per time-step
2024-05-14 16:03:00 - INFO     - async_re.openmm_async_re       - Worker using Reference OpenMM platform
2024-05-14 16:03:03 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r0/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:04 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r1/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:05 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r2/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:07 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r3/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:08 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r4/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:09 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r5/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:10 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r6/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:12 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r7/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:13 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r8/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:14 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r9/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:15 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r10/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:17 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r11/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:18 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r12/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:19 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r13/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:20 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r14/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:21 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r15/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:23 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r16/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:24 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r17/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:25 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r18/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:26 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r19/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:27 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r20/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:28 - INFO     - async_re.openmm_async_re       - Loading checkpointfile r21/eralpha-2e-3a_ckpt.xml
2024-05-14 16:03:32 - INFO     - async_re.openmm_async_re       - Running with a 2.000000 fs time-step with bonded forces integrated 2 times per time-step
2024-05-14 16:03:32 - INFO     - async_re.openmm_async_re       - Worker using CUDA OpenMM platform
```
However, my output file from the slurm scheduler throws the error mentioned in the title of this issue:
```
cat run.sh.e471 
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Warning: importing 'simtk.openmm' is deprecated.  Import 'openmm' instead.
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/shared/miniconda3/envs/atm8.1.1/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/shared/miniconda3/envs/atm8.1.1/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/shared/AToM-OpenMM/ommworker.py", line 293, in openmm_worker
    self._openmm_worker_makecontext()
  File "/shared/AToM-OpenMM/ommworker.py", line 251, in _openmm_worker_makecontext
    self.simulation = Simulation(self.topology, self.system, self.integrator, self.platform, self.platform_properties)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/miniconda3/envs/atm8.1.1/lib/python3.12/site-packages/openmm/app/simulation.py", line 106, in __init__
    self.context = mm.Context(self.system, self.integrator, platform, platformProperties)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/miniconda3/envs/atm8.1.1/lib/python3.12/site-packages/openmm/openmm.py", line 12171, in __init__
    _openmm.Context_swiginit(self, _openmm.new_Context(*args))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
openmm.OpenMMException: Error loading CUDA module: CUDA_ERROR_UNSUPPORTED_PTX_VERSION (222)
```
So does this mean that I can only carry out a restart on the original 1x-GPU node instead of the 8-GPU node, even though they both have the same GPU? I think I identified my issue below, as they are running on different versions of the Nvidia driver and CUDA (11 vs. 12), but wanted to get confirmation from you. Thanks.
```
(atm8.1.1) [centos@modbind-dy-modbind-1 ~]$ nvidia-smi
Tue May 14 16:25:29 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.141.03   Driver Version: 470.141.03   CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:18:00.0 Off |                    0 |
| N/A   25C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla T4            Off  | 00000000:19:00.0 Off |                    0 |
| N/A   27C    P8    10W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  Tesla T4            Off  | 00000000:35:00.0 Off |                    0 |
| N/A   25C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla T4            Off  | 00000000:36:00.0 Off |                    0 |
| N/A   25C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   4  Tesla T4            Off  | 00000000:E7:00.0 Off |                    0 |
| N/A   26C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   5  Tesla T4            Off  | 00000000:E8:00.0 Off |                    0 |
| N/A   26C    P8     8W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   6  Tesla T4            Off  | 00000000:F4:00.0 Off |                    0 |
| N/A   25C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   7  Tesla T4            Off  | 00000000:F5:00.0 Off |                    0 |
| N/A   25C    P8     9W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```
and for the single-GPU:
```
(atm8.1.1) [centos@modbind-dy-modbind-cr-0-1 ~]$ nvidia-smi
Tue May 14 16:36:22 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.129.03             Driver Version: 535.129.03   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
| N/A   46C    P0              71W /  70W |    238MiB / 15360MiB |     99%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      4220      C   AToM worker                                 234MiB |
+---------------------------------------------------------------------------------------+
```

**Comment by egallicc** [comment]
I am not sure, this is an OpenMM issue. 

Downgrading the CUDA version to 11.4 or lower should work with both GPU setups. Try specifying the CUDA version during the OpenMM installation. Something like `conda install -c conda-forge cudatoolkit==11.2 openmm ...`
